TASK: "sem_seg_3d"
MODEL:
  TYPE: "PN2SSG"
  PN2SSG:
    in_channels: 3
    num_centroids: (8192, 2048, 512, 128)
DATASET:
  ROOT_DIR: "data/ScanNet/cache_3d"
  TYPE: "ScanNet3DScene"
  TRAIN: "train"
  VAL: "val"
  ScanNet3DScene:
    use_color: True
DATALOADER:
  NUM_WORKERS: 2
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.002
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (24000, 32000)
  MAX_ITERATION: 40000
TRAIN:
  BATCH_SIZE: 8
  LOG_PERIOD: 100
  SUMMARY_PERIOD: 100
  CHECKPOINT_PERIOD: 1000
  MAX_TO_KEEP: 3
  AUGMENTATION: (("CropPad", 32768), "RandomRotateZ",)
VAL:
  BATCH_SIZE: 8
  PERIOD: 1000
  REPEATS: 3
  AUGMENTATION: (("CropPad", 32768),)
